name: Update Database

on: push
jobs:
  update_hadiths:
    name: "Hadiths DB Updater"
    runs-on: "ubuntu-latest"
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10.x'
    - name: "Fetch hadiths data"
      run: |
        git pull
        wget https://sunnah.com/HadithTable.sql.gz
        sudo systemctl start mysql.service
        mysql -u root -proot -e "create database hadiths;"
        gunzip -c HadithTable.sql.gz | mysql -u root -proot "hadiths"
        rm -f HadithTable.sq*
        python -m pip install tqdm requests html2text mysql-connector-python
        cd parser 
        python parser.py --hadiths
        cd ../
    - name: "Commit DB files"
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add .
        git commit -m "[update]: Push Updated Hadith DB files" -a
    - name: "Push files"
      uses: ad-m/github-push-action@master
  update_quran_sc:
    name: "Quran scripts DB Updater"
    runs-on: "ubuntu-latest"
    needs: update_hadiths
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10.x'
    - name: "Fetch all quran translations data"
      run: |
        git pull
        python -m pip install tqdm requests html2text mysql-connector-python
        cd parser 
        python parser.py --q_trans_main --translations
        cd ../
    - name: "Fetch quran arabic data"
      run: |
        python -m pip install tqdm requests html2text mysql-connector-python
        cd parser 
        python parser.py --q_ar_trans
        cd ../
    - name: "Commit DB files"
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add .
        git commit -m "[update]: Push Updated Quran Scripts DB files" -a
    - name: "Push files"
      uses: ad-m/github-push-action@master
  update_quran_ch:
    name: "Quran chapters DB Updater"
    runs-on: "ubuntu-latest"
    needs: [update_hadiths, update_quran_sc]
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10.x'
    - name: "Fetch quran chapters data"
      run: |
        git pull
        python -m pip install tqdm requests html2text mysql-connector-python
        cd parser 
        python parser.py --chapters --multi_lang_chapters
        cd ../
    - name: "Commit DB files"
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add .
        git commit -m "[update]: Push Updated Quran Chapters DB files" -a
    - name: "Push files"
      uses: ad-m/github-push-action@master
  update_quran_ln:
    name: "Quran languages DB Updater"
    runs-on: "ubuntu-latest"
    needs: [update_hadiths, update_quran_sc, update_quran_ch]
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10.x'
    - name: "Fetch quran languages data"
      run: |
        git pull
        python -m pip install tqdm requests html2text mysql-connector-python
        cd parser 
        python parser.py --lang
        cd ../
    - name: "Commit DB files"
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add .
        git commit -m "[update]: Push Updated Quran Languages DB files" -a
    - name: "Push files"
      uses: ad-m/github-push-action@master
